version: "3"
services:

  cmangos-web-api:
    image: killerwife/cmangos-web-api:latest-linux
    restart: always
    ports:
      - "7191:8080"
      - "7443:443"
    environment:
      - "ASPNETCORE_URLS=https://+;http://+"
      - "ASPNETCORE_HTTPS_PORT=443"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cmangos-web-api.pfx"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=TODO"
      - "ASPNETCORE_ENVIRONMENT=development"
      - "ConnectionStrings:Realmd=server=host.docker.internal,3306; database=tbcrealmd; user=mangos; password=mangos"
      - "ConnectionStrings:Cms=server=host.docker.internal,3306; database=tbccms; user=mangos; password=mangos"
      - "ConnectionStrings:World=server=host.docker.internal,3306; database=tbcmangos; user=mangos; password=mangos"
      - AuthConfig:JwtPrivate="TODO PEM PRIVATE"
      - AuthConfig:JwtPublic="TODO PEM PUBLIC"
      - WebsiteConfig:VerifyEmailUrl="TODO_PUBLIC_URI/emailVerifiedSuccess"
      - WebsiteConfig:PasswordRecoveryUrl="TODO_PUBLIC_URI/forgotpassword/form"
      - WebsiteConfig:ReCaptchaSecret="PRIVATE PART OF RECAPTCHA KEYS"
      - EmailConfig:Host=""
      - EmailConfig:Port=""
      - EmailConfig:RequireSsl=""
      - EmailConfig:Email=""
      - EmailConfig:Password=""
      - EmailConfig:SenderEmail=""
      - EmailConfig:SenderAlias=""
      - DbcConfig:DirectoryPath=/opt/wotlk/dbc/
    volumes:
      - "./cmangos-web-api/cmangos-web-api.pfx:/app/cmangos-web-api.pfx"
      - "./cmangos-web-api/logs/:/app/logs/"
      - "C:/maps/wotlk/dbc:/opt/wotlk/dbc"