curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3483.jpg > public/3483.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3521.jpg > public/3521.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3519.jpg > public/3519.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3518.jpg > public/3518.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3522.jpg > public/3522.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3520.jpg > public/3520.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3523.jpg > public/3523.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3430.jpg > public/3430.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3433.jpg > public/3433.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3524.jpg > public/3524.jpg
curl https://wow.zamimg.com/images/wow/tbc/maps/enus/original/3525.jpg > public/3525.jpg